=== NCEAS/metadig-engine/src/main/resources/schemas/schema1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="https://nceas.ucsb.edu/mdqe/v1" xmlns:tns="https://nceas.ucsb.edu/mdqe/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="check" type="tns:check"/>
  <xs:element name="run" type="tns:run"/>
  <xs:element name="suite" type="tns:suite"/>
  <xs:element name="status" type="tns:runStatus"/>
  <xs:element name="error" type="tns:errorDescription"/>

  <xs:complexType name="systemMetadata">
    <xs:sequence>
      <xs:element name="originMemberNode" type="xs:string" minOccurs="0"/>
      <xs:element name="rightsHolder" type="xs:string" minOccurs="0"/>
      <xs:element name="group" type="xs:string" minOccurs="0"/>
      <xs:element name="dateUploaded" type="xs:dateTime" minOccurs="0"/>
      <xs:element name="formatId" type="xs:string" minOccurs="0"/>
      <xs:element name="obsoletes" type="xs:string" minOccurs="0"/>
      <xs:element name="obsoletedBy" type="xs:string" minOccurs="0"/>
      <xs:element name="seriesId" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="check">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="type" type="xs:string" minOccurs="0"/>
      <xs:element name="level" type="tns:level" minOccurs="0"/>
      <xs:element name="environment" type="xs:string" minOccurs="0"/>
      <xs:element name="code" type="xs:string" minOccurs="0"/>
      <xs:element name="library" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="inheritState" type="xs:boolean" minOccurs="0"/>
      <xs:element name="selector" type="tns:selector" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="dialect" type="tns:dialect" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="selector">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="xpath" type="xs:string" minOccurs="0"/>
      <xs:element name="jsonpath" type="xs:string" minOccurs="0"/>
      <xs:element name="subSelector" type="tns:selector" minOccurs="0"/>
      <xs:element name="namespaces" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="namespace" type="tns:namespace" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="namespaceAware" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="namespace">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="prefix" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dialect">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="xpath" type="xs:string" minOccurs="0"/>
      <xs:element name="jsonpath" type="tns:jsonpathType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="jsonpathType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="match" type="xs:string" use="optional">
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="output">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="result">
    <xs:sequence>
      <xs:element name="check" type="tns:check" minOccurs="0"/>
      <xs:element name="timestamp" type="xs:dateTime" minOccurs="0"/>
      <xs:element name="output" type="tns:output" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="status" type="tns:status" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="run">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="timestamp" type="xs:dateTime"/>
      <xs:element name="objectIdentifier" type="xs:string" minOccurs="0"/>
      <xs:element name="suiteId" type="xs:string" minOccurs="0"/>
      <xs:element name="result" type="tns:result" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="suite">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="namespaces" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="namespace" type="tns:namespace" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="check" type="tns:check" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="level">
    <xs:restriction base="xs:string">
      <xs:enumeration value="OPTIONAL"/>
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="METADATA"/>
      <xs:enumeration value="REQUIRED"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 'status' applies to individual checks -->
  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FAILURE"/>
      <xs:enumeration value="SUCCESS"/>
      <xs:enumeration value="ERROR"/>
      <xs:enumeration value="SKIP"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 'runStatus' applies to the entire run -->
  <xs:simpleType name="runStatus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SUCCESS"/>
      <xs:enumeration value="PROCESSING"/>
      <xs:enumeration value="ERROR"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="errorDescription">
    <xs:simpleContent>
      <xs:extension base="xs:string">
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== NCEAS/metadig-engine/src/main/resources/checks/methods.present.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe/v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe/v1 ../schemas/schema1.xsd">
	<id>check.methods.present.1</id>
	<name>Methods</name>
	<description>All datasets should contain a methods section or a link to a separate methods document.</description>
	<type>interpretation</type>
	<level>REQUIRED</level>
	<environment>rscript</environment>
	<code><![CDATA[
  library(metadig)

  check <- function() {
      badStepCount <- 0
      # Recommended minimum word count
      minWordCount <- 7
      # Recommended maximum word count
      maxWordCount <- 20

      # Check that a methods section is present for the dataset
      if (!methodsPresent) {
          return(list(status = "FAILURE",
                      output = "A methods section is not present, so unable to check method step description word lengths."))
      }

      if (methodStepCount > 0) {
          for (iDescr in 1:length(methodStepDescription)) {
              thisDescr <- methodStepDescription[[iDescr]]
              wordCount <- length(unlist(strsplit(thisDescr, "\\s+", perl = TRUE)))
              if (wordCount < minWordCount) {
                  badStepCount <- badStepCount + 1
              }
          }
      } else {
          # No methodSteps defined (shouldn't happen, it's a required element for methods)
          return(list(status = "FAILURE",
                      output = "No method step descriptions are present."))
      }

      if (badStepCount > 0) {
          return(list(status = "FAILURE",
                      output = sprintf("%d of %d method step descriptions have fewer than the minimum recommended %d words.", badStepCount, methodStepCount, minWordCount)))
      } else {
          return(list(status = "SUCCESS",
                      output = sprintf("All method step descriptions are at least %d words long.", minWordCount)))
      }
  }

  result <- check()

  mdq_result <- list(status = result$status,
                     output = list(list(value = result$output)))
  ]]></code>
	<selector>
		<name>methodsPresent</name>
		<xpath>boolean(/eml/dataset/methods)</xpath>
	</selector>
	<selector>
		<name>methodStepCount</name>
		<xpath>count(/eml/dataset/methods/methodStep)</xpath>
	</selector>
	<selector>
		<name>methodStepDescription</name>
		<xpath>/eml/dataset/methods/methodStep</xpath>
		<subSelector>
			<name>msd</name>
			<xpath>./description//para/text()</xpath>
		</subSelector>
	</selector>
	<dialect>
		<name>eml</name>
		<xpath>boolean(/*[local-name() = 'eml'])</xpath>
	</dialect>
</mdq:check>

=== NCEAS/metadig-engine/src/main/resources/checks/attribute.names.differ.xml
<?xml version="1.0" encoding="UTF-8"?>
<mdq:check xmlns:mdq="https://nceas.ucsb.edu/mdqe"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://nceas.ucsb.edu/mdqe ../schemas/schema1.xsd">
	<id>check.attribute.definitions.differ.1</id>
	<name>Attribute name differs from attribute description.</name>
	<description>Check that each entity name and definition are not identical.</description>
	<type>interpretation</type>
	<level>REQUIRED</level>
	<environment>rscript</environment>
	<code><![CDATA[
check <- function() {
  library(base)
  # varialbe defined by MQE from the <xpath> selectors.
  # "attributeName" - the names of each data entity
  # "attributeDefinition" - the names of each data entity
  
  values <- list()
  attrCount <- 0
  if (length(attributeName) > 0) {
    for(iAttr in 1:length(attributeName)) {
      attrName <- tolower(as.character(attributeName[[iAttr]]))
      attrDef <- tolower(as.character(attributeDefinition[[iAttr]]))
      if(!is.na(attrName) && !is.na(attrDef)) {
        attrCount <- attrCount + 1
        if(attrName == attrDef) {
          values[[length(values)+1]] <- attributeName[[iAttr]]
        }
      }
    }
  }
  
  quoteStyle <- getOption("useFancyQuotes")
  options("useFanceyQuotes" = FALSE)
  
  if(length(values) > 0) {
    return(list(status="FAILURE", values=list(value=sprintf("These attributes have identical names and definitions: %s", paste(sQuote(unlist(values)), collapse=", ")))))
  } else {
    return(list(status="SUCCESS", values=list(value=sprintf("All %d attributes have valid definitions", attrCount))))
  }

  options("useFancyQuotes" = quoteStyle)
}

result <- check()
mdq_result <- list(status=result$status, output=list(result$values))
]]></code>

	<!-- Don't need a subSelector for entityName, as this element is required, 
		so their won't be entities that are selected that don't have this value, 
		and therefor no 'blank' values. -->
	<selector>
		<name>attributeName</name>
		<xpath>/eml/dataset/dataTable/attributeList/attribute</xpath>
		<subSelector>
			<name>attributeNameSubSelector</name>
			<xpath>./attributeName</xpath>
		</subSelector>
	</selector>
	<selector>
		<name>attributeDefinition</name>
		<xpath>/eml/dataset/dataTable/attributeList/attribute</xpath>
		<subSelector>
			<name>attributeDefinitionSubSelector</name>
			<xpath>./attributeDefinition</xpath>
		</subSelector>
	</selector>
	<dialect>
		<name>eml</name>
		<xpath>boolean(/*[local-name() = 'eml'])</xpath>
	</dialect>
</mdq:check>
